### ISSUE TITLE
Rendering of placeholders in edit view is broken

### ISSUE THREAD

**Issue by faebser** [divio/django-cms#3475]
I'm using the following structure in a project:
``` python
{% block content %}
        <article class="detail">
        {% placeholder intro %}
            <div class="article-content">
                {% placeholder content %}
                <div class="footnotes">
                    {% placeholder footnotes %}
                </div>
            </div>
        </div> <!-- closing of article-wrapper inside of intro !-->
        <aside id="sidebar" class="sidebar-detail">
            {% placeholder internal-links %}
            {% placeholder external-links %}
            {% placeholder ads %}
        </aside>
        </article>
{% endblock content %}
```
Sadly neither the placeholder content nor the placeholder footer show up in the edit view.

![placeholder_error_01](https://cloud.githubusercontent.com/assets/333862/4468399/69d59f04-48fd-11e4-9161-612ae1ca8ef0.png)

I think it is related to the css-styles of .article-content and #sidebar. Below are the rendered root-tags of the placeholders.

```html
<div class="cms_dragarea cms_dragarea-4" style="opacity: 1; top: -5px; left: -150px; width: 150px;"> <!-- placeholder content --> 
<div class="cms_dragarea cms_dragarea-8" style="opacity: 1; top: 223px; left: 750.5px; width: 710px;"> <!-- placeholder intro -->
<div class="cms_dragarea cms_dragarea-9" style="opacity: 1; top: -5px; left: -150px; width: 150px;"> <!-- placeholder footnotes -->

```

```css
.article-content {
margin-top: 60px;
position: relative;
padding-right: 25px;
clear: both;
}

#sidebar {
width: 188px;
float: left;
margin-top: -4px;
margin-right: -214px;
margin-left: 26px;
}
```

I'm using
Django==1.6.5
django-cms==3.0.3
