### ISSUE TITLE
[3.4.2] css class .cms-draggable-disabled on parent module

### ISSUE THREAD

**Issue by tgckpg** [divio/django-cms#5906]
### Summary
I was trying to create a base frame plugin which looked something like this:
![image](https://cloud.githubusercontent.com/assets/5273654/24182066/1b881776-0efa-11e7-88c1-a7fbc05b5e43.png)

The `BaseFrame`'s  `allow_children` is set to `False` but the child plugin "ContentPlugin`'s allow_children is set to `True`.

Like so:
```python
class BaseFramePlugin( CMSPluginBase ):
    ...
    allow_children = False
    child_classes = [ "HeaderPlugin", "ContentPlugin", "FooterPlugin" ]
    form = BaseFrameForm

class ContentPlugin( CMSPluginBase ):
    ...
    render_template = "elements/content.html"
    parent_classes = [ "BaseFramePlugin" ]
    allow_children = True
```

### Expected behaviour
![image](https://cloud.githubusercontent.com/assets/5273654/24182381/7fd1e426-0efc-11e7-96db-32ab34afb0d7.png)
Elements under ContentPlugin should be visible.

#### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/5273654/24182066/1b881776-0efa-11e7-88c1-a7fbc05b5e43.png)
Elements under `ContentPlugin` is hidden because of the parent module `BaseFramePlugin`'s `allow_chuildren` set to `False`. Hence applying the class `.cms-draggable-disabled` which acidentally matches this selector for the `ContentPlugin`:
```css
div.cms .cms-structure .cms-draggable-disabled .cms-draggables, div.cms .cms-structure .cms-draggable-disabled .cms-droppable {
    display: none !important;
}
```

Which in turns hides the ContentPlugin's children.

#### Environment

* Python version: 3.6.0
* Django version: 1.8.17
* django CMS version: 3.4.2
